package com.amith.springjpa.serviceimpl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.amith.springjpa.dao.ItemsRepository;
import com.amith.springjpa.model.Items;
import com.amith.springjpa.service.ItemService;

@Service
public class ServiceImpl implements ItemService
{
	 // This means to get the bean called ItemsRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	
	@Autowired
	private ItemsRepository itemsrepo;
	
	public ServiceImpl(ItemsRepository itemsrepo) {
		super();
		this.itemsrepo = itemsrepo;
	}

	public String add(String id,String name)
	{
		Items n = new Items();
	  	n.setId(Integer.parseInt(id));
	    n.setName(name);
	    itemsrepo.save(n);
	    return "Saved";
	}
	
	public Iterable<Items> getAll() {
	    // This returns a JSON or XML with the Items
	    return itemsrepo.findAll();
	}
	public Object getById(String id)
	{
	return itemsrepo.findById(Integer.parseInt(id));
	}
	
	public String deleteItem(String id)
	{
		int n = Integer.parseInt(id);
		itemsrepo.deleteById(n);
		return "Deleted";
	}
}
